CREATE OR REPLACE FUNCTION F_TRANSCODE(inCMUSE_DIV IN VARCHAR2,
									   inCMUSE_ID  IN VARCHAR2									   
 									  )RETURN VARCHAR2 IS
/*
	功能：用來轉換CDSHARENO中文的欄位
*/
	R_PARAM       CDSHARENO.CMUSE_NAME%TYPE;
BEGIN
	IF  inCMUSE_DIV IS NULL OR 
		inCMUSE_ID IS NULL THEN
		R_PARAM := '';
		
	ELSE
		BEGIN
			SELECT CMUSE_NAME
			  INTO R_PARAM
			  FROM CDSHARENO
			 WHERE CMUSE_DIV = inCMUSE_DIV
			   AND CMUSE_ID = inCMUSE_ID;
			EXCEPTION WHEN NO_DATA_FOUND THEN
				R_PARAM := inCMUSE_ID;
		END;            
	END IF;            
	RETURN R_PARAM;            
END;        
/              